server:
  port: 0 #Random Port
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: ${user}        # username, password are retrieved from hashicorp vault
    password: ${pass}
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888   # Config Server Location
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
#actuator 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  