server:
  port: 0 #Random Port
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    #actuator 
management:
  endpoints:
    web:
      exposure:
        include: "*"